spring:
  application:
    name: knowledgebase
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:file:./testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        hibernate:
          dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      timeout: 30
jwt:
  security:
    key: ${JWT_KEY}
    expiration: 86400000